---
- hosts: localhost
  become: true
  become_user: root
  
  tasks:
  
   - name: Deploy to Test Environment
     shell: scp /workspace/SampleProject/SampleProject_Project/CI-CD/Deploy_Ansible_Demo/target/*.war ec2-user@52.221.230.18:/usr/share/tomcat8/webapps
     
- hosts: tomcat
  become: true
  become_user: root
  
  tasks:
  
   - name: Restart tomcat
     service: name=tomcat8 state=restarted


